### ISSUE TITLE
Make it possible to receive floating point and integer numbers as well

### ISSUE THREAD

**Issue by KGergo88** [KGergo88/RDB_Diplomaterv_Monitor#13]
### Description
For many uses cases it would make sense to transmit measurement data that contains floatin point numbers. Currently it is not clear whether this is supported and tested in the project.

### Todo
- [ ] Investigate whether the currently implemented protocols support float type
- [ ] Update the protocol implementations if needed
- [ ] Extend the unit tests to test the processing and exporting of float type
