### ISSUE TITLE
Generalize the connection and protocol handling

### ISSUE THREAD

**Issue by KGergo88** [KGergo88/RDB_Diplomaterv_Monitor#19]
### Description

For the project to be able to handle different protocols and network connections and to be able to freely combine these, it is required to generalise the protocol and network connection handling.

### Todo

- [x] The protocols and connections should be handled via common interface classes by the Backend
- [x] The GUI needs to be updated to allow the user for selecting a protocol - network connection pair the diagrams are sent on
- [x] The SW needs to be able to handle multiple pairs concurrently

**Comment by KGergo88** [comment]
This issue depends on the #36 as we need at least two protocols or connection types for this to make sense.

**Comment by KGergo88** [comment]
The work has started on the branch [GeneralizeTheProtocolAndConnectionHandling_#19](https://github.com/KGergo88/RDB_Diplomaterv_Monitor/tree/GeneralizeTheProtocolAndConnectionHandling_%2319).
