### ISSUE TITLE
Integrate CI tools for the project

### ISSUE THREAD

**Issue by KGergo88** [KGergo88/RDB_Diplomaterv_Monitor#25]
### TODO
  - Take a look at the following products (and others on https://github.com/marketplace):
    - Codecov https://codecov.io
      - It might not support C++
    - Coveralls https://coveralls.io/
    - Travis https://travis-ci.org
      - This could run CppCheck http://cppcheck.sourceforge.net/
      - This could create coverage reports with gcov and lcov
  - Evaluate the integration of these

### Tools that will be integrated:
  - [x] TravisCI
    - [x] Create builds with different OSs, compilers, library versions --> at the moment two different compiler build is enough
    - [x] This shall build with gcov enabled
    - [x] This shall run the cppcheck on the code
    - [x] Required QMake changes
      - [x] Make the building of tests optional with a switch
  - [x] Coveralls

### Discovered issues:
  - We need GCC-8 for the std::filesystem --> Rework the Configuration class to use the Qt classes so older GCC versions could  be used as well
  - QMake: "CONFIG += c++17" is only supported since Qt5.12+ --> Figure out how to install different Qt versions in Travis

**Comment by KGergo88** [comment]
Changes were done on the branch TravisCI then this branch got merged into UnitTesting.
The different GCC variant builds are disabled to save build time, they can be re-enabled later when merging into master.
