### ISSUE TITLE
Setup a GitHub actions for the project

### ISSUE THREAD

**Issue by KGergo88** [KGergo88/RDB_Diplomaterv_Monitor#27]
### Description
Currently the project uses TravisCI for the automated tests and Coveralls for the unit test coverage tracking.
Another option would be to use the GitHub actions. It would make sense to switch to it in order to reduce external dependencies. We also experience some issues with the line coverage visualisations.

**GitHub actions docs:**
- Official documentation: https://docs.github.com/en/free-pro-team@latest/actions
- Syntax summary: https://waylonwalker.com/blog/github-actions-syntax

### Todo
- [x] Implement the following features with GitHub Actions
  - [x] Building the project on Linux (e.g.: Ubuntu) + Run the unit tests with coverage analysis
    - [x] Add Linux job with QMake
    - [x] Add Linux job with CMake
  - [x] Building the project on Windows + Run the unit tests with coverage analysis
    - [x] Add Windows job with CMake
  - [x] Add CMake support for the project
  - [x] Add an action or app that removes the merged branches (either a GitHub action or the Baumpfleger)
  - [x] Run CppCheck and set errors
  - [ ] ~~Follow the coverage results across different commits~~ This feature is not needed.
  - [x] Is it possible to separate the different tests and builds to different actions? This would make it easier to see in a PR what went wrong.
  - [x] Edit the repository settings so only PRs where the checks are passing are allowed to be merged (see https://stackoverflow.com/a/58655352/4085930)
  - [ ] ~~Add badges with Badge action (https://github.com/marketplace/actions/badge-action)~~ This will be done in #43 
  - [x] Setup a security check workflow (https://github.com/KGergo88/RDB_Diplomaterv_Monitor/security/code-scanning)
- [x] Remove TravisCI and Coveralls:
  - [x] Revoke access rights for these tools
  - [x] Remove the TravisCI and Coveralls related files from the repo

**Comment by KGergo88** [comment]
For the windows based jobs CMake is needed as a build system as QMake is not suitable for building projects from CMD on Windows and using QtCreator is suggested.

**Comment by KGergo88** [comment]
The coverage result tracking like what we had with Coveralls is not needed anymore and wont be done.

**Comment by KGergo88** [comment]
Reopening the issue as the Baumpfleger is not working properly.

**Comment by KGergo88** [comment]
Instead of the Baumpfleger the built-in GitHub feature will be used for automatic branch deletions:
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-the-automatic-deletion-of-branches

**Comment by KGergo88** [comment]
The automatic branch deletion was setup and the Baumpfleger was removed.
