### ISSUE TITLE
Add a simple text based protocol to the project to display continuous measurement results

### ISSUE THREAD

**Issue by KGergo88** [KGergo88/RDB_Diplomaterv_Monitor#30]
### Requirements:
- [x] - The protocol shall be based on the MDP protocol.
- [x] - The name shall be CMDP - Continous Measurement Data Protocol
- [x] - It shall be message based instead a single transmission like the MDP
- [x] - It shall support transmissions that include only some of the DataLines but not all of them

### TODO:
- [ ] - Implement SW
- [ ] - Add unit tests for the implemented code
- [ ] - Update the readme with the documentation of the new protocol

**Comment by KGergo88** [comment]
### Protocol design:

**Comment by KGergo88** [comment]
### CMDP - Continous Measurement Data Protocol documentation:

- This protocol is used for data reception trough the serial port, the received data can later on be stored in the filesystem in the MDP format
- It is simple and can be implemented on microcontrollers with limited resources as well
- One data transmission is called a session, that contains data for one diagram
- A session is built up by the following parts:
    - Start pattern
    - Optionally the diagram title
    - The names of the measured quantities and the horizontal axis title
    - The measured values with the horizontal axis values
    - End pattern

The data needs to be formatted the following way in order to be processed by the program:
```
<<<START>>>
<DIAGRAM_TITLE>
"X_AXIS_TITLE","Y0_AXIS_TITLE",...,"Yn_AXIS_TITLE",
"X_AXIS_DATA0","Y0_AXIS_DATA0",...,"Yn_AXIS_DATA0",
.
.
.
"X_AXIS_DATAn","Y0_AXIS_DATAn",...,"Yn_AXIS_DATAn",
<<<END>>>
```

The following requirements have to be fulfilled:
  - The " symbols are not part of the format they are only marking the beginning and the end of an element
  - The measurement data is always starting with the pattern "<<<START>>>"
  - Then the optional diagram title is transmitted, which can be omitted if not needed, in which case a title will be generated for the diagram.
  - Then the headline is transmitted:
    - Every headline element is followed by a comma "," and there are no whitespaces before between and after the elements
    - The headline describes how many different signals were measured and their names
    - There has to be always at least two headline elements transmitted: the common X axis, which is the horizontal axis and at least one Y axis
    - The headline elements:
      - can only contain alphanumeric characters (0..9, A..Z, a..z)
  - Then the headline the measured data is transmitted:
    - Every dataline element is followed by a comma "," and there are no whitespaces before between and after the elements
    - There has to be as many elements in a data line as there was in the headline
    - The data line elements are the values that were measured at the same time
    - All the measured signal values in the data line belong to the first data line element, the common X axis value
    - The data line elements:
      - are integer values
      - can have an optional "+" or "-" sign as a prefix, for example "+25" or "-568"
      - without a sign prefix are considered positive
  - The measurement data is always ending with the pattern "<<<END>>>"
  - This data, starting with the start pattern until the end of the end pattern is called a session that contains all data needed to describe a diagram
  - If there was an error detected in one of the lines then the whole session is invalid

Examples for a session without diagram title and two measured signals:
```
<<<START>>>
u32TimeMs,u32SetValue,u32ActualValue,
0,4000,0,
10,4000,500,
20,4000,1000,
30,4000,1500,
40,4000,2000,
50,4000,2500,
60,4000,3000,
70,4000,3500,
80,4000,4000,
<<<END>>>
```

Examples for a session with diagram title and one measured signal:
```
<<<START>>>
<Living room daily temperature>
u32TimeHour,u8RoomTemperature,
0,15,
2,17,
4,19,
6,18,
8,20,
1022,
12,24,
14,26,
16,24,
18,22,
20,20,
22,18,
<<<END>>>
```

**Comment by KGergo88** [comment]
# CMDP - Continous Measurement Data Protocol session examples:
Examples for a session without diagram title and two measured signals:
 **_INCLUDE SESSION EXAMPLE HERE_** 

Examples for a session with diagram title and one measured signal:
**_INCLUDE SESSION EXAMPLE HERE_**
