### ISSUE TITLE
Add badges to the README

### ISSUE THREAD

**Issue by KGergo88** [KGergo88/RDB_Diplomaterv_Monitor#43]
### Description
During the switch from TravisCI+Coveralls to GitHub Actions in #27 the badges were removed from the README.md. We should create new badges about the status of the commit (whether it builds on Linux or Windows) and the coverage results and about the static code analysis results (CppCheck).

Links that might contain useful info for this topic:
- https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/adding-a-workflow-status-badge
- https://itnext.io/github-actions-code-coverage-without-third-parties-f1299747064d
- http://shields.io/
- https://github.com/marketplace/actions/badge-action

### Todo
- [ ] Evaluate the listed tools and HowTos
- [ ] Add badges for the build status
- [ ] Add a badge for the coverage results
- [ ] Add badge for the CppCheck results
